name: Full Stack CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    
permissions:
  contents: write 

jobs:
  # -----------------------------
  # Phase 1: Continuous Integration
  # -----------------------------
  ci-build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Test Frontend Build
      working-directory: ./client
      run: |
        npm install
        npm run build

    - name: Test Backend Integrity
      working-directory: ./server
      run: npm install

  # -----------------------------
  # Phase 2: Continuous Deployment
  # -----------------------------
  cd-deploy-frontend:
    needs: ci-build-test 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Compile Production Build
      working-directory: ./client
      run: |
        npm install
        npm run build --base=/ExamApp/

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./client/dist